/**
 * PROJECT: Dengue Dynamic Transmission & HEOR Model (Dengue DTM 2025)
 * DESCRIPTION: Pre-Calibrated Policy & Research Scenarios from PLOS Medicine 2025
 */

export const SCENARIO_PRESETS = [
  {
    id: 'baseline',
    name: 'Status Quo (No Intervention)',
    description: 'Natural endemic dengue transmission in Thailand without vaccination or enhanced vector control.',
    vacEnabled: false,
    routineAge: 11,
    coverage: 87,
    catchUpEnabled: false,
    catchUpMin: 6,
    catchUpMax: 14,
    testBeforeVac: false,
    vecEnabled: false,
    vecRatioReduction: 0,
    vecBitingReduction: 0,
    vaccinePrice: 30,
    discountRate: 3.0,
    perspective: 'societal'
  },
  {
    id: 'r11_base',
    name: 'R11: Routine at Age 11 (Base Case)',
    description: 'Routine vaccination with TAK-003 at age 11 years (87% coverage, 2-dose regimen) without catch-up.',
    vacEnabled: true,
    routineAge: 11,
    coverage: 87,
    catchUpEnabled: false,
    catchUpMin: 11,
    catchUpMax: 11,
    testBeforeVac: false,
    vecEnabled: false,
    vecRatioReduction: 0,
    vecBitingReduction: 0,
    vaccinePrice: 30,
    discountRate: 3.0,
    perspective: 'societal'
  },
  {
    id: 'r9_base',
    name: 'R9: Routine at Age 9',
    description: 'Routine vaccination with TAK-003 at age 9 years (87% coverage, 2-dose regimen).',
    vacEnabled: true,
    routineAge: 9,
    coverage: 87,
    catchUpEnabled: false,
    catchUpMin: 9,
    catchUpMax: 9,
    testBeforeVac: false,
    vecEnabled: false,
    vecRatioReduction: 0,
    vecBitingReduction: 0,
    vaccinePrice: 30,
    discountRate: 3.0,
    perspective: 'societal'
  },
  {
    id: 'r9_catchup_9_14',
    name: 'R9 + Catch-Up 9–14y (High Impact)',
    description: 'Routine vaccination at age 9 + Year 1 catch-up campaign for children aged 9 to 14 years at 87% coverage.',
    vacEnabled: true,
    routineAge: 9,
    coverage: 87,
    catchUpEnabled: true,
    catchUpMin: 9,
    catchUpMax: 14,
    testBeforeVac: false,
    vecEnabled: false,
    vecRatioReduction: 0,
    vecBitingReduction: 0,
    vaccinePrice: 30,
    discountRate: 3.0,
    perspective: 'societal'
  },
  {
    id: 'r6_catchup_6_14',
    name: 'R6 + Catch-Up 6–14y (Broad Cohort)',
    description: 'Routine vaccination at primary school entry (Age 6) + Year 1 catch-up for school children aged 6 to 14 years.',
    vacEnabled: true,
    routineAge: 6,
    coverage: 87,
    catchUpEnabled: true,
    catchUpMin: 6,
    catchUpMax: 14,
    testBeforeVac: false,
    vecEnabled: false,
    vecRatioReduction: 0,
    vecBitingReduction: 0,
    vaccinePrice: 30,
    discountRate: 3.0,
    perspective: 'societal'
  },
  {
    id: 'vector_wolbachia',
    name: 'Vector Control (Wolbachia Program)',
    description: 'Biological vector control program yielding 40% reduction in biting rate and 30% reduction in mosquito density.',
    vacEnabled: false,
    routineAge: 11,
    coverage: 0,
    catchUpEnabled: false,
    catchUpMin: 6,
    catchUpMax: 14,
    testBeforeVac: false,
    vecEnabled: true,
    vecRatioReduction: 30,
    vecBitingReduction: 40,
    annualVecCost: 15000000,
    vaccinePrice: 30,
    discountRate: 3.0,
    perspective: 'societal'
  },
  {
    id: 'integrated_combo',
    name: 'Integrated Strategy (Vaccine + Wolbachia)',
    description: 'Comprehensive dual strategy combining R11 routine TAK-003 vaccination with targeted Wolbachia vector suppression.',
    vacEnabled: true,
    routineAge: 11,
    coverage: 87,
    catchUpEnabled: false,
    catchUpMin: 11,
    catchUpMax: 11,
    testBeforeVac: false,
    vecEnabled: true,
    vecRatioReduction: 30,
    vecBitingReduction: 40,
    annualVecCost: 15000000,
    vaccinePrice: 30,
    discountRate: 3.0,
    perspective: 'societal'
  },
  {
    id: 'pre_screen_serotest',
    name: 'Pre-Vaccination Screening Strategy',
    description: 'Pre-vaccination rapid serological screening (95% sensitivity, 90% specificity). Only seropositive individuals receive vaccine.',
    vacEnabled: true,
    routineAge: 9,
    coverage: 87,
    catchUpEnabled: false,
    catchUpMin: 9,
    catchUpMax: 9,
    testBeforeVac: true,
    testSensitivity: 95,
    testSpecificity: 90,
    screeningCost: 5.0,
    vecEnabled: false,
    vecRatioReduction: 0,
    vecBitingReduction: 0,
    vaccinePrice: 30,
    discountRate: 3.0,
    perspective: 'societal'
  }
];
